[package]
name = "snowvault-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
egui-modal = "0.6.0"
env_logger = "0.11.6"
rfd = "0.15.2"
secrecy = "0.10.3"
snowvault = { path = "../snowvault" }
